### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by andreasphil** [anphil/bookmark-manager#3]
Implement user sign up, sign in and sign out using [Devise](https://github.com/plataformatec/devise).

**Gemfile:**

```
# Use Devise for authentification
gem 'devise','3.4.1'
```
- [x] Validation via opt-in
- [x] `letter_opener` gem during development

**Removed tasks**
- delete route `edit_user_password`

**Comment by sportz** [comment]
[ ] Validation via opt-in

**Comment by sportz** [comment]
route is needed when resetting password via mail
